### PR TITLE
Updating Sanity Source

### PR DESCRIPTION
**Pull request by pingevt**
## Description

Updating Sanity Source to reflect a few desired changes in how we handle sources:

- Handling pagination in result files.
- Custom queries for Sanity Source.

## Related Issue

#32 
#23

## Motivation and Context

how many files we are saving and how big they are.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Review Checklist:

- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] My change requires a test to make sure it continually works.
- [ ] I have added tests accordingly.

### CODE REVIEW

**Comment by pingevt** [comment]
@benjaminbojko this should be ready to review

**Comment by benjaminbojko** [comment]
Thanks @pingevt ! Have Jason or Katie been able to test everything here?

**Comment by pingevt** [comment]
I haven't had anyone else test it yet... but let me throw it in Slack.

**Comment by benjaminbojko** [comment]
@pingevt I'd like to shorten the naming of `combinePaginatedFiles` somehow. Left a few suggestions here for `combineContentResults()`, which might be good to keep consistent: https://github.com/bluecadet/launchpad/issues/32#issuecomment-1227567698

How about `mergePages` in options, and `mergeResults()` in `ContentSource`?

**Comment by pingevt** [comment]
@benjaminbojko forgot about that one...

I think `.combine()` works to get rid of the redundancy and I think `mergePages` sounds like a better option...

**Comment by pingevt** [comment]
Vars/Method renamed

**Pull request merged**
